# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TopUpEmoney' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'BottomSheet', :git => 'https://github.com/weitieda/bottom-sheet.git'
  pod 'Alamofire'

  # Pods for TopUpEmoney

end
